// Flights choosing
export const CHOOSE_ALL_FLIGHTS = 'CHOOSE_ALL_FLIGHTS';
export const CHOOSE_FLIGHTS_WITHOUT_STOPS = 'CHOOSE_FLIGHTS_WITHOUT_STOPS';
export const CHOOSE_FLIGHTS_WITH_ONE_STOP = 'CHOOSE_FLIGHTS_WITH_ONE_STOP';
export const CHOOSE_FLIGHTS_WITH_TWO_STOPS = 'CHOOSE_FLIGHTS_WITH_TWO_STOPS';
export const CHOOSE_FLIGHTS_WITH_THREE_STOPS = 'CHOOSE_FLIGHTS_WITH_THREE_STOPS';

// Currency choosing
export const CHOOSE_UAH_CURRENCY = 'CHOOSE_UAH_CURRENCY';
export const CHOOSE_USD_CURRENCY = 'CHOOSE_USD_CURRENCY';
export const CHOOSE_EUR_CURRENCY = 'CHOOSE_EUR_CURRENCY';
