// Actions with flights
export const FLIGHT_CONDITION_CHOICE = 'FLIGHT_CONDITION_CHOICE';
export const REQUEST_FLIGHTS = 'REQUEST_FLIGHTS';
export const RECEIVE_FLIGHTS = 'RECEIVE_FLIGHTS';
export const RECEIVE_FLIGHTS_MOCK = 'RECEIVE_FLIGHTS_MOCK';

// Actions with currencies
export const CHOOSE_CURRENCY = 'CHOOSE_CURRENCY';
export const CONVERT_UAH_TO_USD = 'CONVERT_UAH_TO_USD';
export const CONVERT_UAH_TO_EUR = 'CONVERT_UAH_TO_EUR';
